#!/bin/bash
# This script's framework was created using makescript 
# version v0.14.7, dated 2018-11-12
# Makescript and its accompanying scripts are copyrighted
# by Aetesaki (c) 2018
# 
# archive (c) 2018 aetesaki
#
# ##################################################
# HISTORY:
# ##################################################
#
# * 2018-11-17 - v0.0.0  - First Creation
#
# ##################################################
# Initializing constants and variables
# ##################################################
# Setting constants
version="v0.0.0"            # Sets version variable
lastEdited="2018-11-17"     # Sets last edited variable" $scriptNamePath
# Declaring variables
# Declare all variables to be used in the script 
declare lastModifiedDate
declare cutoffDate=$1
declare destination=$2
# ##################################################
# short help function
# ##################################################
shorthelp() {
    # Edit as required
    echo "Usage: archive date destination
       archive --help
       archive --version"
}
# ##################################################
# -- help
# ##################################################
if [ "$1" == "--help" ]; then
    shorthelp
    # Write options and explanations
    echo "
   --help                 Displays this text and exit.
   --version              Displays the version of the script and exit."
    # Write information on arguments afterwards
    echo "
    This script will move all files in current directory, which hasn't been 
    modified since before date to destination.
    Destination must be a valid directory-"
    # Write examples as required
    echo "
    archive 2016-1-1 FolderB
    will move all files older than 1 January 2016 to FolderB."
    exit 0
fi 
# ##################################################
# -- version
# ##################################################
if [ "$1" == "--version" ]; then
    echo "archive ${version}, dated ${lastEdited}
(c) 2018 aetesaki"
    exit 0
fi
# ##################################################
# Main section
# ##################################################
# if destination is not a directory
if [ ! -d $destination ]; then
    # exit with error
    echo "ERROR: $destination is not a directory."
    exit 1
fi
# For each file in directiory
for file in * ; do
    # if file is not a directory
    if [ ! -d $file ]; then
        # get the last modify date
        lastModifiedDate=$( stat $file | grep Modify | cut -d" " -f2 )
        # if lastModifiedDate older than cutoffDate
        if [[ "$lastModifiedDate" < "$cutoffDate" ]]; then
            # move file to destination
            mv $file $destination
        fi
    fi
done
    
